/*
 * Tapdata OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: moa-v1.1.0-117-g6b02a67
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tapdata.sdk.api;

import io.tapdata.sdk.ApiException;
import io.tapdata.sdk.ApiClient;
import io.tapdata.sdk.model.FINCUSTOMER;
import io.tapdata.sdk.model.Filter;
import io.tapdata.sdk.model.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FinCustomerV1Api
 */
@Ignore
public class FinCustomerV1ApiTest {

    private final ApiClient apiClient = new ApiClient(
        "your_client_id",
        "your_client_secret",
        "api_url", // http://127.0.0.1:3080
        "auth_url" // http://127.0.0.1:3030/oauth/token
    );
    private final FinCustomerV1Api api = new FinCustomerV1Api(apiClient);

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fINCUSTOMERV1ControllerCreateTest() throws ApiException {
        FINCUSTOMER FINCUSTOMER = new FINCUSTOMER();
        FINCUSTOMER response = api.fINCUSTOMERV1ControllerCreate(FINCUSTOMER);

        // TODO: test validations
    }
    
    /**
     * delete record by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fINCUSTOMERV1ControllerDeleteByIdTest() throws ApiException {
        String id = new String();
        api.fINCUSTOMERV1ControllerDeleteById(id);

        // TODO: test validations
    }
    
    /**
     * get record by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fINCUSTOMERV1ControllerFindByIdTest() throws ApiException {
        String id = new String();
        FINCUSTOMER response = api.fINCUSTOMERV1ControllerFindById(id);

        // TODO: test validations
    }
    
    /**
     * get record list by page and limit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fINCUSTOMERV1ControllerFindPageTest() throws ApiException {
        Filter filter = new Filter();
        InlineResponse200 response = api.fINCUSTOMERV1ControllerFindPage(filter);

        // TODO: test validations
    }
    
    /**
     * update record by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fINCUSTOMERV1ControllerUpdateByIdTest() throws ApiException {
        String id = new String();
        FINCUSTOMER FINCUSTOMER = new FINCUSTOMER();
        api.fINCUSTOMERV1ControllerUpdateById(id, FINCUSTOMER);

        // TODO: test validations
    }
    
}
