/*
 * Tapdata OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: moa-v1.1.0-115-g56235c8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tapdata.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiV1CONSUMPTIONLOGFields
 */
public class ApiV1CONSUMPTIONLOGFieldsTest {
    private final ApiV1CONSUMPTIONLOGFields model = new ApiV1CONSUMPTIONLOGFields();

    /**
     * Model tests for ApiV1CONSUMPTIONLOGFields
     */
    @Test
    public void testApiV1CONSUMPTIONLOGFields() {
        // TODO: test ApiV1CONSUMPTIONLOGFields
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'CUSTOMER_ID'
     */
    @Test
    public void CUSTOMER_IDTest() {
        // TODO: test CUSTOMER_ID
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'shop'
     */
    @Test
    public void shopTest() {
        // TODO: test shop
    }

}
