/*
 * Tapdata OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: moa-v1.1.0-115-g56235c8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tapdata.sdk.api;

import io.tapdata.sdk.ApiCallback;
import io.tapdata.sdk.ApiClient;
import io.tapdata.sdk.ApiException;
import io.tapdata.sdk.ApiResponse;
import io.tapdata.sdk.Configuration;
import io.tapdata.sdk.Pair;
import io.tapdata.sdk.ProgressRequestBody;
import io.tapdata.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.tapdata.sdk.model.FINCUSTOMER;
import io.tapdata.sdk.model.Filter1;
import io.tapdata.sdk.model.InlineResponse2001;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FinCustomerV1Api {
    private ApiClient localVarApiClient;

    public FinCustomerV1Api() {
        this(Configuration.getDefaultApiClient());
    }

    public FinCustomerV1Api(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for fINCUSTOMERV1ControllerCreate
     * @param FINCUSTOMER  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> FIN_CUSTOMER model instance </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fINCUSTOMERV1ControllerCreateCall(FINCUSTOMER FINCUSTOMER, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = FINCUSTOMER;

        // create path and map variables
        String localVarPath = "/api/v1/FIN_CUSTOMER";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "OAuth2" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, _callback);
    }


    @SuppressWarnings("rawtypes")
    private okhttp3.Call fINCUSTOMERV1ControllerCreateValidateBeforeCall(FINCUSTOMER FINCUSTOMER, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerCreateCall(FINCUSTOMER, _callback);
        return localVarCall;

    }

    /**
     * 
     * 
     * @param FINCUSTOMER  (optional)
     * @return FINCUSTOMER
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> FIN_CUSTOMER model instance </td><td>  -  </td></tr>
     </table>
     */
    public FINCUSTOMER fINCUSTOMERV1ControllerCreate(FINCUSTOMER FINCUSTOMER) throws ApiException {
        ApiResponse<FINCUSTOMER> localVarResp = fINCUSTOMERV1ControllerCreateWithHttpInfo(FINCUSTOMER);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param FINCUSTOMER  (optional)
     * @return ApiResponse&lt;FINCUSTOMER&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> FIN_CUSTOMER model instance </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FINCUSTOMER> fINCUSTOMERV1ControllerCreateWithHttpInfo(FINCUSTOMER FINCUSTOMER) throws ApiException {
        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerCreateValidateBeforeCall(FINCUSTOMER, null);
        Type localVarReturnType = new TypeToken<FINCUSTOMER>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param FINCUSTOMER  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> FIN_CUSTOMER model instance </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fINCUSTOMERV1ControllerCreateAsync(FINCUSTOMER FINCUSTOMER, final ApiCallback<FINCUSTOMER> _callback) throws ApiException {

        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerCreateValidateBeforeCall(FINCUSTOMER, _callback);
        Type localVarReturnType = new TypeToken<FINCUSTOMER>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fINCUSTOMERV1ControllerDeleteById
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> FIN_CUSTOMER DELETE success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fINCUSTOMERV1ControllerDeleteByIdCall(String id, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = new Object();

        // create path and map variables
        String localVarPath = "/api/v1/FIN_CUSTOMER/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "OAuth2" };
        return localVarApiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, _callback);
    }


    @SuppressWarnings("rawtypes")
    private okhttp3.Call fINCUSTOMERV1ControllerDeleteByIdValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling fINCUSTOMERV1ControllerDeleteById(Async)");
        }
        

        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerDeleteByIdCall(id, _callback);
        return localVarCall;

    }

    /**
     * delete record by id
     * 
     * @param id  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> FIN_CUSTOMER DELETE success </td><td>  -  </td></tr>
     </table>
     */
    public void fINCUSTOMERV1ControllerDeleteById(String id) throws ApiException {
        fINCUSTOMERV1ControllerDeleteByIdWithHttpInfo(id);
    }

    /**
     * delete record by id
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> FIN_CUSTOMER DELETE success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> fINCUSTOMERV1ControllerDeleteByIdWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerDeleteByIdValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * delete record by id (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> FIN_CUSTOMER DELETE success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fINCUSTOMERV1ControllerDeleteByIdAsync(String id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerDeleteByIdValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for fINCUSTOMERV1ControllerFindById
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> FIN_CUSTOMER model instance </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fINCUSTOMERV1ControllerFindByIdCall(String id, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = new Object();

        // create path and map variables
        String localVarPath = "/api/v1/FIN_CUSTOMER/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "OAuth2" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, _callback);
    }


    @SuppressWarnings("rawtypes")
    private okhttp3.Call fINCUSTOMERV1ControllerFindByIdValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling fINCUSTOMERV1ControllerFindById(Async)");
        }
        

        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerFindByIdCall(id, _callback);
        return localVarCall;

    }

    /**
     * get record by id
     * 
     * @param id  (required)
     * @return FINCUSTOMER
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> FIN_CUSTOMER model instance </td><td>  -  </td></tr>
     </table>
     */
    public FINCUSTOMER fINCUSTOMERV1ControllerFindById(String id) throws ApiException {
        ApiResponse<FINCUSTOMER> localVarResp = fINCUSTOMERV1ControllerFindByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * get record by id
     * 
     * @param id  (required)
     * @return ApiResponse&lt;FINCUSTOMER&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> FIN_CUSTOMER model instance </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FINCUSTOMER> fINCUSTOMERV1ControllerFindByIdWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerFindByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<FINCUSTOMER>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * get record by id (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> FIN_CUSTOMER model instance </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fINCUSTOMERV1ControllerFindByIdAsync(String id, final ApiCallback<FINCUSTOMER> _callback) throws ApiException {

        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerFindByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<FINCUSTOMER>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fINCUSTOMERV1ControllerFindPage
     * @param filter  (optional, default to null)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Object of page data, result.data is FIN_CUSTOMER model instances, result.total is model count. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fINCUSTOMERV1ControllerFindPageCall(Filter1 filter, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = new Object();

        // create path and map variables
        String localVarPath = "/api/v1/FIN_CUSTOMER";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (filter != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPair(buildQuery(filter)));
        }

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "OAuth2" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, _callback);
    }

    private Map<String, String> buildQuery(Filter1 filter) {
        Map<String, String> filterMap = new HashMap<>();
        Object where = filter.getWhere();
        Integer limit = filter.getLimit();
        Integer skip = filter.getSkip();
        List<String> order = filter.getOrder();
        if (where != null && where instanceof Map && !((Map) where).isEmpty()) {
            for (Map.Entry<String, Object> entry : ((Map<String, Object>) where).entrySet()) {
                filterMap.put("filter[where]" + entry.getKey(), entry.getValue().toString());
            }
        }

        if (limit != null && limit > 0) {
            filterMap.put("filter[limit]", limit.toString());
        }

        if (skip != null && skip >= 0) {
            filterMap.put("filter[skip]", skip.toString());
        }

        if (order != null && !order.isEmpty()) {
            for (int i = 0; i < order.size(); i++) {
                filterMap.put("filter[order][" + i + "}", order.get(i));
            }
        }

        return filterMap;
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fINCUSTOMERV1ControllerFindPageValidateBeforeCall(Filter1 filter, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerFindPageCall(filter, _callback);
        return localVarCall;

    }

    /**
     * get record list by page and limit
     * 
     * @param filter  (optional, default to null)
     * @return InlineResponse2001
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Object of page data, result.data is FIN_CUSTOMER model instances, result.total is model count. </td><td>  -  </td></tr>
     </table>
     */
    public InlineResponse2001 fINCUSTOMERV1ControllerFindPage(Filter1 filter) throws ApiException {
        ApiResponse<InlineResponse2001> localVarResp = fINCUSTOMERV1ControllerFindPageWithHttpInfo(filter);
        return localVarResp.getData();
    }

    /**
     * get record list by page and limit
     * 
     * @param filter  (optional, default to null)
     * @return ApiResponse&lt;InlineResponse2001&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Object of page data, result.data is FIN_CUSTOMER model instances, result.total is model count. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InlineResponse2001> fINCUSTOMERV1ControllerFindPageWithHttpInfo(Filter1 filter) throws ApiException {
        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerFindPageValidateBeforeCall(filter, null);
        Type localVarReturnType = new TypeToken<InlineResponse2001>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * get record list by page and limit (asynchronously)
     * 
     * @param filter  (optional, default to null)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Object of page data, result.data is FIN_CUSTOMER model instances, result.total is model count. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fINCUSTOMERV1ControllerFindPageAsync(Filter1 filter, final ApiCallback<InlineResponse2001> _callback) throws ApiException {

        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerFindPageValidateBeforeCall(filter, _callback);
        Type localVarReturnType = new TypeToken<InlineResponse2001>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fINCUSTOMERV1ControllerUpdateById
     * @param id  (required)
     * @param FINCUSTOMER  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> FIN_CUSTOMER PATCH success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fINCUSTOMERV1ControllerUpdateByIdCall(String id, FINCUSTOMER FINCUSTOMER, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = FINCUSTOMER;

        // create path and map variables
        String localVarPath = "/api/v1/FIN_CUSTOMER/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "OAuth2" };
        return localVarApiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, _callback);
    }


    @SuppressWarnings("rawtypes")
    private okhttp3.Call fINCUSTOMERV1ControllerUpdateByIdValidateBeforeCall(String id, FINCUSTOMER FINCUSTOMER, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling fINCUSTOMERV1ControllerUpdateById(Async)");
        }
        

        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerUpdateByIdCall(id, FINCUSTOMER, _callback);
        return localVarCall;

    }

    /**
     * update record by id
     * 
     * @param id  (required)
     * @param FINCUSTOMER  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> FIN_CUSTOMER PATCH success </td><td>  -  </td></tr>
     </table>
     */
    public void fINCUSTOMERV1ControllerUpdateById(String id, FINCUSTOMER FINCUSTOMER) throws ApiException {
        fINCUSTOMERV1ControllerUpdateByIdWithHttpInfo(id, FINCUSTOMER);
    }

    /**
     * update record by id
     * 
     * @param id  (required)
     * @param FINCUSTOMER  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> FIN_CUSTOMER PATCH success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> fINCUSTOMERV1ControllerUpdateByIdWithHttpInfo(String id, FINCUSTOMER FINCUSTOMER) throws ApiException {
        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerUpdateByIdValidateBeforeCall(id, FINCUSTOMER, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * update record by id (asynchronously)
     * 
     * @param id  (required)
     * @param FINCUSTOMER  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> FIN_CUSTOMER PATCH success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fINCUSTOMERV1ControllerUpdateByIdAsync(String id, FINCUSTOMER FINCUSTOMER, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = fINCUSTOMERV1ControllerUpdateByIdValidateBeforeCall(id, FINCUSTOMER, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
